### ISSUE TITLE
rockspec fails to install

### ISSUE THREAD

**Issue by daurnimator** [leegao/see.lua#3]
```
$ sudo luarocks install see
Installing https://luarocks.org/see-0.1-0.rockspec
Cloning into 'see.lua'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 19 (delta 2), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (19/19), 18.05 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.

Error: Build error: Failed installing see/reader.lua in /usr/lib/luarocks/rocks-5.3/see/0.1-0/lua/see/reader.lua: see/reader.lua: No such file or directory
```

**Comment by leegao** [comment]
Thanks for flagging this, I'm a complete noob at `luarocks`, but this should be fixed after luarocks backs up its rocks tonight.

**Comment by daurnimator** [comment]
About your rockspec:

  - You didn't write (or remove) the description
  - Your home page is a git url (use a https one!)
  - Your license says MIT/X11, but you are actually under the MIT/expat license. Use MIT instead
  - You left the default comment after license field
  - Please don't edit already uploaded non-scm rockspecs: instead increment the version number (bit after `-`)
  - If you use `luarocks upload` it should create and upload a .src.rock file that means end users can skip the `git clone`.

**Comment by daurnimator** [comment]
Btw, looking at your rockspec commit: a better fix might have been to add a `source.directory` field.
This way `luarocks make` from the cloned source would continue to work

**Comment by daurnimator** [comment]
rockspec is better now :)

One thing to mention is that the tag should just be 0.1: the '-1' is the version of the rockspec (which you might need to refine independently of the source code)

The other thing you can do for pure-lua libraries is run 'luarocks pack see' => this will create a '.all.rock' file, which can be uploaded manually to luarocks.org (via e.g. https://luarocks.org/modules/leegao/see/0.1-1/upload). I also tend to upload these .all.rock files to the 'releases' section on github (https://github.com/leegao/see.lua/releases/tag/v0.1-1)
